version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: sevarecover-opensearch-backend
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data-backend:/usr/share/opensearch/data

volumes:
  opensearch-data-backend:
